apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cast-service
  name: cast-service
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
  selector:
    io.kompose.service: cast-service