apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast
  labels:
    io.kompose.service: cast-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path