apiVersion: v1
kind: Service
metadata:
  name: cast-db
  labels:
    io.kompose.service: cast-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: cast-db
  type: ClusterIP