apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: movie-service
  name: movie-service
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8000
  selector:
    io.kompose.service: movie-service