apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie
  labels:
    io.kompose.service: movie-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path