apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      io.kompose.service: nginx
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: {{ .Values.nginx.image }}
          name: nginx
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          securityContext:
            readOnlyRootFilesystem: false
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config