apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dev
data:
  default.conf: |
    server {
      listen 8081;

      location /api/v1/movies {
        proxy_pass http://movie-service:8001/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast-service:8002/api/v1/casts;
      }

    }